// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "client-20190117191220-hostingbucket",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "http://client-20190117191220-hostingbucket.s3-website-ap-northeast-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "ap-northeast-1:71220a66-e12e-4ab3-8f6b-c636a9eec35a",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_ZZzyjYZRy",
    "aws_user_pools_web_client_id": "791ag9v626n94q5m3tqs74qjn8"
};


export default awsmobile;
